### ISSUE TITLE
Static instruction sets

### ISSUE THREAD

**Issue by nickgarfield** [clockwork-xyz/clockwork#104]
When we added support for dynamic instruction threads, we unlocked a lot of new development possibilities. We also threw away our previous threading model which relied on a pre-defined list of instructions. This may have been too extreme of a pivot. 

There are many use-cases where a static list of instructions would be preferable to dynamic threading. For example, users want to compose instructions of various programs together in a client-side frontend. 

We could support both dynamic and static instruction sets by refactoring `kickoff_instruction` and `next_instruction` out of `Thread` and introducing a new enum:

```rs
pub enum InstructionSet {
  Dynamic {
    kickoff_instruction: InstructionData,
    next_instruction: Option<InstructionData>
  },
  Static {
    current_idx: i64,
    instructions: Vec<InstructionData>
  }
}

pub struct Thread {
  pub instruction_set: InstructionSet,
  // ...
}
```

In `thread_exec`, we would need to update the instruction set according to its type. It may also make sense to touch up the `ThreadResponse` schema.

**Comment by enzoampil** [comment]
I think another issue with Dynamic instruction threads is that it seems that you can't solve "transaction size limit" issues by breaking an ix down into multiple ixs.

Even for the case where we have multiple thread instructions (eg 3), we still need to input all of the accounts for all 3 instructions into the first thread instruction, which will cause us to have the same transaction size limit issues compared to when we fit all the instructions' logic within a single instruction.

more concretely:

`thread_ix1()` requires `thread_ix1_accounts`, `thread_ix2_accounts`, and `thread_ix3_accounts` as inputs since `thread_ix2` needs to be initialized within `thread_ix1()`, and `thread_ix3` needs to be initialized within `thread_ix2()`

if all three instructions have say > 40 accounts in total then calling `thread_ix1()` will always lead to a "transaction size limit exceeded error".

Of course, if we could somehow pass lookup tables to a Thread for the validators to use for transaction compression then this takes out the need to "separate into multiple instructions".

I believe above this won't be an issue for *static instruction sets* as long a:
1. Validators can invoke each instruction through a separate transaction (as opposed to bundling each into the same tx)
2. We allow for instructions to be *appended* into the instructions `Vec` of a `Thread` within `thread_create` - although not a hard requirement since versioned transaction compression from the thread creator's side can also solve this

**Comment by nickgarfield** [comment]
So for dynamic instructions, you don't actually need to have the next instruction's accounts as input on your prior instruction. You only need to be able to provide the **pubkeys** of the second instruction's accounts. In other words, `ix1` needs a way lookup or derive the pubkeys needed by `ix2`, but does not need all of its accounts. The worker will take care of simulating `ix1` and `ix2` and then pack all the accounts needed by both instructions into a single transaction. This simulation + packing process continues recursively until either the thread has no more instructions to execute or the transaction has hit the size limits. If the latter scenario, the workers continue processing the thread from where the last transaction left off.

**Comment by enzoampil** [comment]
> This simulation + packing process continues recursively until either the thread has no more instructions to execute or the transaction has hit the size limits

@nickgarfield noted on this.

Regarding providing pubkeys though, even then you'd still need to access those from somewhere, either from account inputs that contain those pubkeys, or even a lookup table account that's made to store those pubkeys (though yeah this is a solution).

**Comment by nickgarfield** [comment]
Yeah, the other way is if you have a predictable pattern in your PDA seeds. There's a few places in the network program where we use use auto-incrementing integers in our PDA derivations so that it makes sequential processing of accounts fairly easy.

https://github.com/clockwork-xyz/clockwork/blob/15896115a65fdc02605495f31869cbe39f2b2f69/programs/network/src/instructions/snapshot_entry_create.rs#L125

**Comment by enzoampil** [comment]
Gotcha - either way, think I'll stick to waiting for static instructions for simplicity.

**Comment by nickgarfield** [comment]
https://github.com/clockwork-xyz/clockwork/pull/180
